# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:36
from __future__ import unicode_literals

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20161030_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(validators=[bank.models.validate_number]),
        ),
    ]
